resources:
 repositories:
   - repository: NOP_4_40
     type: github
     endpoint: Bungalow64
     name: Bungalow64/NOP-4.40
   - repository: NOP_4_30
     type: github
     endpoint: Bungalow64
     name: Bungalow64/NOP-4.30

trigger:
- main

variables:
  buildConfiguration: 'Release'

pool:
 vmImage: 'ubuntu-latest'

steps:
- checkout: NOP_4_40
  submodules: true
- checkout: NOP_4_30
  submodules: true

- script: dir $(Build.SourcesDirectory)

- powershell: Get-ChildItem -Path '$(Build.SourcesDirectory)' -recurse

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\NOP-4.30\**\*.sln'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration) - NOP 4.30'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)\NOP-4.40\**\*.sln'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration) - NOP 4.40'
  
- powershell: Get-ChildItem -Path '$(Build.SourcesDirectory)' -recurse