resources:
 repositories:
   - repository: NOP_4_40
     type: github
     endpoint: Bungalow64
     name: Bungalow64/NOP-4.40
   - repository: NOP_4_30
     type: github
     endpoint: Bungalow64
     name: Bungalow64/NOP-4.30

trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
- checkout: NOP_4_40
  submodules: true
- checkout: NOP_4_30
  submodules: true

- script: dir $(Build.SourcesDirectory)

- powershell: Get-ChildItem -Path '$(Build.SourcesDirectory)' -recurse