resources:
 repositories:
   - repository: NOP_4_40
     type: github
     endpoint: Bungalow64
     name: Bungalow64/NOP_4.40     
   - repository: NOP_4_30
     type: github
     endpoint: Bungalow64
     name: Bungalow64/NOP_4.30

trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
- checkout: NOP_4_40
- checkout: NOP_4_30

- script: dir $(Build.SourcesDirectory)